# Site configuration for GitHub Pages
title: "Cristina Luna - Planetary Robotics & Space Anthropology"
description: "Planetary Robotics | Off-Earth Anthropologist"
author: "Cristina Luna"
email: "cristina.luna@live.com"

# GitHub Pages configuration - TEMA ESPACIAL
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

# Navigation menu
header_pages:
  - README.md
  - publications.md

# Site metadata
lang: en-US
github:
  repository_url: https://github.com/cristinaluna/cristinaluna.github.io

# Social media
social:
  name: Cristina Luna
  links:
    - https://github.com/cristinaluna
    - https://orcid.org/0000-0002-4781-1965
    - https://www.researchgate.net/profile/Cristina-Luna-Santos
    - https://instagram.com/xrispx
    - https://flickr.com/photos/xrispx

# Enable syntax highlighting
highlighter: rouge
markdown: kramdown

# Custom CSS para colores espaciales
sass:
  sass_dir: _sass
  style: compressed

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

# Collections
collections:
  pages:
    output: true
    permalink: /:name/
